source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 3.1.0'

gem 'rails', '~> 7.0'
gem 'pg', '~> 1.1'
gem 'puma', '~> 6.0'
gem 'redis', '~> 4.0'
gem 'sidekiq', '~> 7.0'
gem 'jwt'
gem 'bcrypt', '~> 3.1.7'
gem 'rack-cors'
gem 'httparty'
gem 'nokogiri'
gem 'chronic'
gem 'geocoder'
gem 'image_processing', '~> 1.2'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-rails_csrf_protection'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
  gem 'factory_bot_rails'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
end

