namespace :authors do
  desc "Pre-seed the authors table with a curated list of known authors (idempotent)"
  task seed: :environment do
    AUTHOR_NAMES = [
      "A.J. Finn", "A.J. Jacobs", "A.K. Mulford", "Abbi Waxman", "Abby Jimenez",
      "Abraham Verghese", "Adalyn Grace", "Adrian Tchaikovsky", "Adrienne Young",
      "Agatha Christie", "Alessandra Olanow", "Alex George", "Alex Hannaford",
      "Alex Landragin", "Alex Michaelides", "Alexandra Andrews", "Alexandra Romanoff",
      "Alexis Henderson", "Alexis Patton", "Alfred Kazin", "Ali Hazelwood", "Ali Shaw",
      "Alice Feeney", "Alice Hoffman", "Alison Espach", "Alison Rose Greenberg",
      "Alistair MacLeod", "Alix E. Harrow", "Alka Joshi", "Allegra Goodman",
      "Allison Ashley", "Ally Carter", "Ally Condie", "Amal El-Mohtar",
      "Amanda Eyre Ward", "Amanda Litman", "Amanda Montell", "Amiee Gibbs",
      "Amor Towles", "Amy Harmon", "Amy Tan", "Amy Tintera", "Analeigh Sbrana",
      "Andrea Eames", "Andrea Pitzer", "Andrew Hunter Murray", "Andy Weir",
      "Angie Kim", "Anissa Gray", "Ann Liang", "Ann Napolitano", "Ann Patchett",
      "Anna Kendrick", "Annabel Monaghan", "Anne Griffin", "Anne Lamott",
      "Anthony Doerr", "Anthony Marra", "Aparna Verma", "Ariel Lawhon",
      "Ariel Sullivan", "Arkady Martine", "Arthur C. Brooks", "Ashlee Vance",
      "Ashley Jordan", "Ashley Elston", "Ashley Poston", "Ashley Winstead",
      "Ava Reid", "Ayşe Kulin", "B.K. Borison", "Bae Myung-hoon", "Barbara Davis",
      "Barbara Bourland", "Barbara Kingsolver", "Barbara O'Neal", "Beatriz Williams",
      "Becca Freeman", "Becky Chambers", "Belle Burden", "Ben Mezrich", "Ben Shattuck",
      "Benjamin Stevenson", "Benjamín Labatut", "Bernhard Schlink",
      "Beth Allison Barr", "Beth O'Leary", "Beth Revis", "Bethany Joy Lenz",
      "Bill Johnson", "Blake Crouch", "Bob Goff", "Bolu Babalola",
      "Brandon Sanderson", "Bree Grenwich", "Brené Brown", "Brian King",
      "Brian Keating", "Brian Greene", "Brian Zahnd", "Brianna Labuskes",
      "Bridget Collins", "Brigitte Knightley", "Brit Bennett", "C Pam Zhang",
      "C.A. Higgins", "C.C. Peñaranda", "C.J. Archer", "C.S. Lewis",
      "Cadwell Turnbull", "Callie Collins", "Callie Hart", "Cameron Stracher",
      "Cara Bastone", "Caragh M. O'Brien", "Carissa Broadbent", "Carley Fortune",
      "Carlos Ruiz Zafón", "Caro Claire Burke", "Carole Stivers", "Caroline Lea",
      "Carsten Henn", "Cassandra Clare", "Catherine Walsh", "Catherine Airey",
      "Catherine Steadman", "Cathey McCrary", "Celeste Ng", "Chandler Baker",
      "Charles Belfoure", "Charlie Kaufman", "Charlotte McConaghy",
      "Charmaine Wilkerson", "Chelsea Abdullah", "Cherise Wolas", "Chloe Benjamin",
      "Chloe Liese", "Chris Bohjalian", "Chris Cleave", "Chris Hadfield",
      "Christelle Dabos", "Christie Tate", "Christina Baker Kline",
      "Christina Lauren", "Christine Coulson", "Christopher L. Hayes",
      "Christopher Paolini", "Claire Heywood", "Claire Keegan", "Claire Lombardo",
      "Claire North", "Clare Chambers", "Clare Leslie Hall", "Clare Pooley",
      "Clarissa Pinkola Estés", "Colleen Hoover", "Colleen Oakley",
      "Colson Whitehead", "Cormac McCarthy", "Crissy Van Meter", "D.L. Soria",
      "Daisy Goodwin", "Dani Francis", "Dani Shapiro", "Daniel Immerwahr",
      "Daniel Kraus", "Danielle L. Jensen", "Danzy Senna", "Daphne du Maurier",
      "Dara Horn", "David Yoon", "David Colbert", "David Deutsch", "David Ellis",
      "David McCullough", "Deanna Raybourn", "Delia Owens", "Demi Winters",
      "Dennis E. Taylor", "Denny S. Bryce", "Devney Perry", "Diana Gabaldon",
      "Donald J. Robertson", "Donna Tartt", "Doris Kearns Goodwin", "Douglas Adams",
      "Edith Eger", "Edmund Morris", "Edward Ashton", "Eiren Caffall", "Elan Mastai",
      "Elena Gorokhova", "Elie Wiesel", "Elif Shafak", "Elinor Cleghorn",
      "Elise Kova", "Elizabeth O'Connor", "Elizabeth Gilbert", "Elizabeth O'Roark",
      "Elizabeth Strout", "Elizabeth Wein", "Elle Cosimano", "Ellen Baker",
      "Ellery Lloyd", "Elodie Harper", "Emily Bain Murphy", "Emily Henry",
      "Emily St. John Mandel", "Emily Stone", "Emily Wibberley", "Emma Brodie",
      "Emma Donoghue", "Emma Grey", "Emma Straub", "Eoin Dempsey", "Eowyn Ivey",
      "Eric Zandona", "Erica Bauermeister", "Erik Larson", "Erika Napoletano",
      "Erika Swyler", "Erin Morgenstern", "Ernest Cline", "Ezra Klein",
      "Fei-Fei Li", "Fiona Davis", "Fiona Valpy", "Frances White", "Frances Cha",
      "Frances Hodgson Burnett", "Frances de Pontes Peebles", "Francis Chan",
      "Frank E. Peretti", "Frank Herbert", "Frank O'Hara", "Fredrik Backman",
      "Freida McFadden", "Frode Grytten", "Fyodor Dostoevsky", "Gabrielle Zevin",
      "Gail Honeyman", "Gareth Brown", "Gary Janetti", "Genevieve Wheeler",
      "George Orwell", "George R.R. Martin", "George Saunders", "Georgia Hunter",
      "Glennon Doyle", "Grace D. Li", "Graeme Simsion", "Grant Ginder",
      "Gretchen McCulloch", "H.G. Parry", "H.G. Wells", "H.M. Wolfe",
      "Hafsah Faizal", "Hank Green", "Hanna Howard", "Hannah Bonam-Young",
      "Hannah Kaner", "Hannah Nicole Maehrer", "Hannah Whitten", "Hanya Yanagihara",
      "Hayley Gelfuso", "Hazel Gaynor", "Heather Morris", "Heather Fawcett",
      "Heather O'Neill", "Heather Webber", "Heidi Heilig", "Helen Hoang",
      "Helen Simonson", "Hernan Diaz", "Hesse Phillips", "Hilary Mantel",
      "Holly Black", "Holly Goddard Jones", "Holly Renee", "Hwang Bo-Reum",
      "Ian Morgan Cron", "Imani Erriu", "India Holton", "Iona Grey", "Isaac Asimov",
      "Isabel Ibañez", "J. Courtney Sullivan", "J. Ryan Stradal", "J.D. Vance",
      "J.K. Rowling", "J.L. Carr", "J.M. Barrie", "J.M. Miro", "J.R.R. Tolkien",
      "Jackie Lau", "Jaclyn Goldis", "Jacqueline Holland", "Jacqueline Carey",
      "Jacqueline Harpman", "Jacqueline Susann", "James Dashner", "James Islington",
      "James Wood", "Jamie Ford", "Jane Austen", "Janella Angeles", "Jason Mott",
      "Jasper Fforde", "Jean Hanff Korelitz", "Jean Kyoung Frazier",
      "Jeff Vandermeer", "Jeff Zentner", "Jeffrey Eugenides", "Jen Hatmaker",
      "Jeneva Rose", "Jennette McCurdy", "Jennifer L. Armentrout",
      "Jennifer Lynn Barnes", "Jenny Bayliss", "Jenny Colgan", "Jenny Jackson",
      "Jess Kidd", "Jessa Hastings", "Jessa Maxwell", "Jesse Q. Sutanto",
      "Jessica Chiccehitto Hindman", "Jessica George", "Jessica Joyce",
      "Jessica Soffer", "Jessie Burton", "Jillian Medoff", "Jo Piazza",
      "Joanna Quinn", "Jodi McAlister", "Joelle Charbonneau", "Johann Hari",
      "John Boyne", "John Green", "John Gwynne", "John Scalzi", "John Steinbeck",
      "Jojo Moyes", "Jonathan Haidt", "Joseph J. Ellis", "Josie Silver",
      "Joss Richard", "Joyce Carol Oates", "Joël Dicker", "Julia Quinn",
      "Julia Whelan", "Julianne MacLean", "Julie Berry", "Juliette Cross",
      "Junot Díaz", "Justin Cronin", "K.A. Linde", "K.J. Ramsey", "K.L. Walther",
      "K.X. Song", "Kaliane Bradley", "Kalie Cassidy", "Karen Dukess",
      "Kassandra Montag", "Kate Clayborn", "Kate Khavari", "Kate Posey",
      "Kate Quinn", "Kate Racculia", "Kate Watson", "Kate Weinberg",
      "Katharine McGee", "Katharine Schellman", "Katherine Arden",
      "Katherine Center", "Katherine May", "Katherine Schwarzenegger Pratt",
      "Katherine Sharp Landdeck", "Kathleen Barber", "Kathryn Stockett",
      "Katie Holt", "Katrine Marçal", "Kazuo Ishiguro", "Kelly Bishop",
      "Kelly Link", "Kelly Rimmer", "Kelsie Sheridan Gonzalez", "Kerri Maniscalco",
      "Kevin Kwan", "Kevin Wilson", "Kiley Reid", "Kimberly Belle", "Kimi Eisele",
      "Kris Vallotton", "Kristan Higgins", "Kristen Ciccarelli", "Kristen Perrin",
      "Kristin Hannah", "Kristin Harmel", "Krysten Ritter", "L.J. Claren",
      "L.M. Montgomery", "Laini Taylor", "Lang Leav", "Laura Dave", "Laura Hankin",
      "Laura Spence-Ash", "Laura Steven", "Lauren Fox", "Lauren Groff",
      "Lauren Oliver", "Lauren Roberts", "Lauren Weisberger", "Laurie Gilmore",
      "Layne Fargo", "Leif Enger", "Leigh Bardugo", "Leigh Stein", "Lev Grossman",
      "Liane Moriarty", "Libby Page", "Lili Anolik", "Lily Brooks-Dalton",
      "Lily King", "Lindsay Ellis", "Lindsay Lynch", "Lisa Grunwald", "Lisa Unger",
      "Liu Cixin", "Liv Constantine", "Liz Moore", "London Sperry",
      "Lori Nelson Spielman", "Louisa May Alcott", "Louise Fein", "Louise Penny",
      "Lucy Foley", "Lucy Gilmore", "Lydia Millet", "Lyla Sage", "Lynne Olson",
      "M.L. Rio", "M.L. Wang", "Madeline Miller", "Mai Corland", "Malcolm Gladwell",
      "Maria Semple", "Marie Benedict", "Marie Brennan", "Marie Lu",
      "Marilyn Vancil", "Marisha Pessl", "Mark Dunn", "Mark Haddon", "Mark Manson",
      "Mark T. Sullivan", "Mark Wolynn", "Markus Zusak", "Martha Wells",
      "Mary Ann Shaffer", "Mary Beth Keane", "Mary Doria Russell",
      "Mary E. Pearson", "Mary Kubica", "Mary Oliver", "Matt Black",
      "Matt Dinniman", "Matt Haig", "Matthew McConaughey", "Matthew Quick",
      "Maureen Johnson", "Maurene Goo", "Max Brooks", "Max Jammer", "May Cobb",
      "Meaghan O'Connell", "Meg Shaffer", "Meg Waite Clayton", "Megan Angelo",
      "Megan Whalen Turner", "Melanie Benjamin", "Merlin Sheldrake",
      "Mhairi McFarlane", "Mia P. Manansala", "Mia Sheridan", "Michael Chabon",
      "Michael Finkel", "Michael J. Gelb", "Michael Ondaatje", "Michaela Carter",
      "Michele Filgate", "Michele Harper", "Michelle Zauner", "Mohsin Hamid",
      "Mona Awad", "Morgan Pager", "N.K. Jemisin", "Nancy Jooyoun Kim",
      "Naoki Higashida", "Naomi Alderman", "Natalie Haynes", "Natasha Pulley",
      "Nathaniel Philbrick", "Neal Stephenson", "Neil Gaiman", "Neil deGrasse Tyson",
      "Niall Williams", "Nicole Krauss", "Nikki Erlick", "Nino Haratischwili",
      "Nita Prose", "Nnedi Okofor", "Ocean Vuong", "Octavia E. Butler",
      "Oliver Sacks", "Olivia Atwater", "Olivie Blake", "Omer Bartov",
      "Orson Scott Card", "Ottessa Moshfegh", "Pam Jenoff", "Paolo Bacigalupi",
      "Patrick Bringley", "Patrick Ness", "Patrick Radden Keefe",
      "Patrick Rothfuss", "Paul Murray", "Paula Lafferty", "Paula McLain",
      "Paulo Coelho", "Penn Cole", "Peter Cawdron", "Peter Heller",
      "Phaedra Patrick", "Philip C. Quaintrell", "Philip K. Dick",
      "Philip Pullman", "Pierce Brown", "Pip Williams", "Prince Harry",
      "R.F. Kuang", "Rachel Cohen", "Rachel Gillig", "Rachel Harrison",
      "Rachel Hawkins", "Rachel Joyce", "Rebecca Makkai", "Rebecca Ross",
      "Rebecca Serle", "Rebecca Yarros", "Renee Carlino", "Rhys Bowen",
      "Richard Osman", "Richard P. Feynman", "Richard Powers", "Richard Rhodes",
      "Rick Rubin", "Riley August", "Rita Chang-Eppig", "Rob Franklin",
      "Robert B. Cialdini", "Robert J. Ray", "Robert Jackson Bennett",
      "Robert Waldinger", "Robin Sloan", "Robyn Harding", "Rochelle Bilow",
      "Ron Chernow", "Rosalia Aguilar Solace", "Roxane Gay", "Rupert Holmes",
      "Ruta Sepetys", "Ruth Hogan", "Ruth Ozeki", "Ruth Reichl", "S.E. Hinton",
      "S.T. Gibson", "Saara El-Arifi", "Sabaa Tahir", "Sally Rooney",
      "Sally Thorne", "Samantha Shannon", "Samantha Sotto Yambao", "Samuel Burr",
      "Sara Nisha Adams", "Sara Wolf", "Sarah A. Parker", "Sarah Addison Allen",
      "Sarah Adler", "Sarah Brooks", "Sarah Damoff", "Sarah Grunder Ruiz",
      "Sarah Haywood", "Sarah J. Maas", "Sarah MacLean", "Sarah Maine",
      "Sarah Morgenthaler", "Sarah Pearse", "Sarah Penner", "Sarah Perry",
      "Sarah Underwood", "Sarah Winman", "Sarajane Case", "Satoshi Yagisawa",
      "Scott Lynch", "SenLinYu", "Serge Brunier", "Shannon Castleton",
      "Shauna Lawless", "Shea Ernshaw", "Shelby Van Pelt", "Shelley Nolden",
      "Shelley Parker-Chan", "Sherry Thomas", "Shirlene Obuobi", "Signe Pike",
      "Simone Soltani", "Simone St. James", "Simu Liu", "Sin Blaché",
      "Sloane Crosley", "Sophie Cousens", "Sophie Kinsella", "Stacia Stark",
      "Stephanie Barron Hall", "Stephanie Foo", "Stephanie Garber", "Stephen King",
      "Stephen E. Ambrose", "Steve Brusatte", "Steven Novella", "Stuart Turton",
      "Sue Lynn Tan", "Sulari Gentill", "Susan Cain", "Susan Orlean",
      "Susanna Clarke", "Susie Yang", "Suzanne Collins", "Suzanne Rindell",
      "Suzanne Stabile", "Sylvain Neuvel", "Sylvia Plath", "T. Kingfisher",
      "T.A. Willberg", "T.J. Klune", "Tara Conklin", "Tara Westover",
      "Tarah DeWitt", "Tasha Suri", "Taylor Jenkins Reid", "Ted Chiang",
      "Ted Dekker", "Terry Pratchett", "Tessa Bickers", "Tessonja Odette",
      "Thao Thai", "Thea Guanzon", "Thomas Cahill", "Thomas Geve", "Tia Williams",
      "Tiffany Crum", "Timothy Mason", "Tosca Lee", "Toshikazu Kawaguchi",
      "Tracy Borman", "Travis Baldree", "Tricia Levenseller", "Téa Obreht",
      "Ursula K. Le Guin", "Uzma Jalaluddin", "V.E. Schwab", "V.L. Bovalino",
      "Val Emmich", "Veronica Henry", "Veronica Rossi", "Veronica Roth",
      "Victoria Aveyard", "Viktor E. Frankl", "Virginia Evans", "Walter Farley",
      "Walter Isaacson", "Will Storr", "William Gay", "William Paul Young",
      "William Strauss", "William Strunk Jr.", "Yiyun Li", "Yume Kitasei",
      "Yōko Ogawa", "Zachary Levi", "Zack Jordan", "bell hooks",
    ].freeze

    created = 0
    skipped = 0

    AUTHOR_NAMES.each do |name|
      author = Author.find_or_initialize_by(name: name)
      if author.new_record?
        author.save!
        created += 1
      else
        skipped += 1
      end
    rescue ActiveRecord::RecordInvalid => e
      puts "  SKIP (invalid): #{name} — #{e.message}"
      skipped += 1
    end

    puts "Done. Created: #{created}, already existed: #{skipped}, total: #{AUTHOR_NAMES.length}"
  end
end
